### ISSUE TITLE
Wrong result for user:Kulinarix

### ISSUE THREAD

**Issue by xqt** [tool-labs/RightToVote#10]
Checking right to vote for user Kulinarix fails. 
https://stimmberechtigung.toolforge.org/?user=Kulinarix&day=14&mon=07&year=2024&hour=11&min=35&mode=bot gives
```
Datum Abstimmung: 14.07.2024 um 11:35:00
Benutzer: Kulinarix
Fehler: Benutzer unbekannt.
```
Without bot mode:
`Benutzer "Kulinarix" existiert nicht.`

Seems that `actor_id` is missing or empty/0

**Comment by Count-Count** [comment]
This issue was fixed after moving to the WMF Gitlab.
